---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: development

commonLabels:
  env: dev
  app.kubernetes.io/managed-by: flux

patches:
  - target:
      kind: Service
      namespace: default
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: development