---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - monitoring.yaml
  - networking.yaml
  - security.yaml
  - nginx-svc.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux