---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
    env: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    env: prod
---
