# roles/flux/templates/nginx-svc.yml.j2
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: production  # Dynamic namespace
  labels:
    env: prod
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80