---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default  # Static value or use <class 'jinja2.utils.Namespace'> if needed
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

