---
- name: Remove conflicting Docker packages
  shell: |
    for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
      sudo apt-get remove -y $pkg
    done
  args:
    warn: false
  register: remove_conflicts
  changed_when: true
  failed_when: false  # Ensure task doesn't fail if no stdout is returned (in check mode)

- name: Show output of removed packages
  debug:
    msg: "{{ remove_conflicts.stdout.splitlines() if remove_conflicts.stdout else 'No packages were removed or task not executed.' }}"
  when: not ansible_check_mode  # Only run this in normal mode, not in check mode

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Install Docker Engine
  apt:
    name: "{{ docker_packages }}"
    state: "{{ docker_packages_state }}"
    update_cache: yes

- name: Setting value of SystemdCgroup
  shell: |
    containerd config default | sudo tee /etc/containerd/config.toml
    sed -i 's|sandbox_image = "registry.k8s.io/pause:3.*"|sandbox_image = "registry.k8s.io/pause:3.10"|g' /etc/containerd/config.toml
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes


