---
- name: Debug join command on worker nodes
  debug:
    msg: "Join command retrieved: {{ join_command }}"

- name: Set join command fact on workers
  set_fact:
    join_command: "{{ hostvars[(hostvars | dict2items | selectattr('value.is_master', 'equalto', true) | first).key].join_command }}"
  delegate_to: "{{ (hostvars | dict2items | selectattr('value.is_master', 'equalto', true) | first).key }}"
  run_once: true

- name: Join worker nodes to the cluster
  become: true
  command: "{{ join_command }}"

- name: Label worker node as 'worker'
  become: true
  command: "kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/worker=true --overwrite"
  delegate_to: "{{ (hostvars | dict2items | selectattr('value.is_master', 'equalto', true) | first).key }}"
  register: label_result  # Debugging
  failed_when: label_result.rc != 0