---
- name: Validate GitHub token
  block:
    - name: Include vaulted secrets
      include_vars:
        file: roles/flux/vars/secrets.yml
        name: secrets
      no_log: true

    - name: Ensure GitHub token is valid
      uri:
        url: "https://api.github.com/repos/yungryce/azure_vmss_cluster"
        method: GET
        headers:
          Authorization: "Bearer {{ github_token }}"
        status_code: 200
      register: token_check
      no_log: true

- name: Check if deploy key already exists
  uri:
    url: "https://api.github.com/repos/yungryce/azure_vmss_cluster/keys"
    method: GET
    headers:
      Authorization: "Bearer {{ github_token }}"
      Accept: "application/vnd.github.v3+json"
    status_code: 200
  register: existing_keys

- name: Add deploy key if not exists
  uri:
    url: "https://api.github.com/repos/yungryce/azure_vmss_cluster/keys"
    method: POST
    headers:
      Authorization: "Bearer {{ github_token }}"
      Accept: "application/vnd.github.v3+json"
    body_format: json
    body:
      title: "flux-deploy-{{ ansible_date_time.date }}"
      key: "{{ lookup('file', '/home/azureuser/.ssh/flux-deploy-key.pub') | trim }}"
      read_only: false
    status_code: 201
  when: 
    - token_check.status == 200
    - hostvars[inventory_hostname].is_master
    - >
        lookup('file', '/home/azureuser/.ssh/flux-deploy-key.pub') | regex_replace(' .*', '') | trim
        not in existing_keys.json | map(attribute='key') | map('regex_replace', ' .*', '') | list

- name: Configure SSH for GitHub
  blockinfile:
    path: /root/.ssh/config
    block: |
      Host github.com
        IdentityFile /root/.ssh/flux-deploy-key
        User git
        IdentitiesOnly yes
    create: yes
    mode: '0600'
  when: hostvars[inventory_hostname].is_master

- name: Push GitOps changes to Git repository
  block:

    - name: Stage all changes
      command: git add .
      args:
        chdir: /home/azureuser/azure_vmss_cluster

    - name: Get list of modified files
      command: git status --porcelain
      args:
        chdir: /home/azureuser/azure_vmss_cluster
      register: git_status
      changed_when: false

    - name: Generate commit message
      set_fact:
        commit_message: |
          Initial GitOps setup: Added infrastructure, apps, and cluster configurations
          Modified files:
          {{ git_status.stdout | regex_replace('^', '      ') }}

    - name: Commit changes with modified files list
      command: >
        git commit -m "{{ commit_message }}"
      args:
        chdir: /home/azureuser/azure_vmss_cluster
      ignore_errors: true  # Allow this to fail if there are no changes

    - name: Push changes to remote repository
      command: git push origin main
      args:
        chdir: /home/azureuser/azure_vmss_cluster
      ignore_errors: true  # Allow this to fail if there are no changes
      environment:
        GIT_SSH_COMMAND: "ssh -i /root/.ssh/flux-deploy-key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
  delegate_to: localhost