---
- name: Setup GitOps directory structure
  delegate_to: localhost
  run_once: true
  block:
    - name: Create base directories
      file:
        path: "{{ gitops_base_path }}/{{ item }}/base"
        state: directory
        owner: "{{ git_owner }}"
        group: "{{ git_group }}"
        mode: "{{ dir_mode }}"
      loop:
        - "infrastructure/base"
        - "apps/base"
        - "clusters/development/flux-system"

    - name: Generate infrastructure kustomization
      template:
        src: "base-kustomization.yaml.j2"
        dest: "{{ gitops_base_path }}/infrastructure/base/kustomization.yaml"
        owner: "{{ git_owner }}"
        group: "{{ git_group }}"
        mode: "{{ file_mode }}"

    - name: Generate namespaces manifest
      template:
        src: "namespaces.yaml.j2"
        dest: "{{ gitops_base_path }}/infrastructure/base/namespaces.yaml"
        owner: "{{ git_owner }}"
        group: "{{ git_group }}"
        mode: "{{ file_mode }}"

    - name: Generate app kustomization
      template:
        src: "apps-kustomization.yaml.j2"
        dest: "{{ gitops_base_path }}/apps/base/kustomization.yaml"
        owner: "{{ git_owner }}"
        group: "{{ git_group }}"
        mode: "{{ file_mode }}"

    - name: Generate nginx resources
      template:
        src: "{{ item.src }}"
        dest: "{{ gitops_base_path }}/apps/base/{{ item.dest }}"
        owner: "{{ git_owner }}"
        group: "{{ git_group }}"
        mode: "{{ file_mode }}"
      loop:
        - { src: "nginx-deployment.yaml.j2", dest: "nginx-deployment.yaml" }
        - { src: "nginx-svc.yml.j2", dest: "nginx-svc.yaml" }
        - { src: "nginx-kustomization.yaml.j2", dest: "kustomization.yaml" }

    - name: Generate cluster kustomization
      template:
        src: "cluster-kustomization.yaml.j2"
        dest: "{{ gitops_base_path }}/clusters/development/flux-system/kustomization.yaml"
        owner: "{{ git_owner }}"
        group: "{{ git_group }}"
        mode: "{{ file_mode }}"

    - name: Generate flux bootstrap manifests
      template:
        src: "{{ item.src }}"
        dest: "{{ gitops_base_path }}/clusters/development/flux-system/{{ item.dest }}"
        owner: "{{ git_owner }}"
        group: "{{ git_group }}"
        mode: "{{ file_mode }}"
      loop:
        - { src: "gotk-components.yaml.j2", dest: "gotk-components.yaml" }
        - { src: "gotk-sync.yaml.j2", dest: "gotk-sync.yaml" }


