---
- name: Install Flux CLI
  when: hostvars[inventory_hostname].is_master
  block:
    - name: Get latest Flux version
      uri:
        url: https://api.github.com/repos/fluxcd/flux2/releases/latest
        return_content: true
      register: flux_latest
      delegate_to: localhost
      run_once: true

    - name: Set Flux version
      set_fact:
        flux_version: "{{ flux_latest.json.tag_name | regex_replace('^v', '') }}"

    - name: Download Flux binary
      get_url:
        url: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_amd64.tar.gz"
        dest: "/tmp/flux.tar.gz"
        mode: "0644"

    - name: Create temporary directory
      file:
        path: "/tmp/flux"
        state: directory
        mode: "0755"

    - name: Extract Flux binary
      unarchive:
        src: "/tmp/flux.tar.gz"
        dest: "/tmp/flux"
        remote_src: true

    - name: Install Flux binary
      become: true
      copy:
        src: "/tmp/flux/flux"
        dest: "/usr/local/bin/flux"
        mode: "0755"
        remote_src: true

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/flux.tar.gz"
        - "/tmp/flux"

    - name: Verify Flux installation
      command: flux --version
      register: flux_version_check
      changed_when: false