---
- name: Clean up old Flux installation
  block:
    - name: Check if flux-system namespace exists
      kubernetes.core.k8s_info:
        kind: Namespace
        name: flux-system
      register: flux_ns
      ignore_errors: true

    - name: Remove flux-system namespace if it exists
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: flux-system
      when: flux_ns.resources is defined and flux_ns.resources | length > 0

    - name: Remove old Flux installation marker
      file:
        path: /etc/flux_bootstrapped
        state: absent

    - name: Wait for namespace termination
      kubernetes.core.k8s_info:
        kind: Namespace
        name: flux-system
      register: flux_ns_check
      until: flux_ns_check.resources | length == 0
      retries: 30
      delay: 10
      when: flux_ns.resources is defined and flux_ns.resources | length > 0

- name: Install Flux CLI
  block:
    - name: Get latest Flux version
      uri:
        url: https://api.github.com/repos/fluxcd/flux2/releases/latest
        return_content: true
      register: flux_latest
      delegate_to: localhost
      run_once: true

    - name: Set Flux version
      set_fact:
        flux_version: "{{ flux_latest.json.tag_name | regex_replace('^v', '') }}"

    - name: Download Flux binary
      get_url:
        url: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_amd64.tar.gz"
        dest: "/tmp/flux.tar.gz"
        mode: "0644"

    - name: Create temporary directory
      file:
        path: "/tmp/flux"
        state: directory
        mode: "0755"

    - name: Extract Flux binary
      unarchive:
        src: "/tmp/flux.tar.gz"
        dest: "/tmp/flux"
        remote_src: true

    - name: Install Flux binary
      become: true
      copy:
        src: "/tmp/flux/flux"
        dest: "/usr/local/bin/flux"
        mode: "0755"
        remote_src: true

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/flux.tar.gz"
        - "/tmp/flux"

    - name: Verify Flux installation
      command: flux --version
      register: flux_version_check
      changed_when: false

- name: Setup Flux prerequisites
  block:
    - name: Create flux-system namespace
      kubernetes.core.k8s:
        name: flux-system
        api_version: v1
        kind: Namespace
        state: present

    - name: Wait for flux-system namespace to be ready
      kubernetes.core.k8s_info:
        kind: Namespace
        api_version: v1
        name: flux-system
        wait: yes
        wait_timeout: 300